### ISSUE TITLE
Arnaud joining Hydra WG

### ISSUE THREAD

**Issue by abailly-iohk** [cardano-scaling/wg-hydra#4]
### Name

Arnaud

### Contact Details

arnaud.bailly@iohk.io

### Initial thoughts

Happy to help steer the future of Hydra, even though I am not involved in its development anymore. I haven't relinquished the hope of finishing hydra-chess

**Comment by ch1bo** [comment]
Added to @cardano-scaling/wg-hydra and listed in README.
